######################################################################
# Automatically generated by qmake (2.01a) Thu May 8 14:46:58 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . include src
INCLUDEPATH += . include

# Input
HEADERS += include/QDialog.h
SOURCES += src/main.cpp src/QDialog.cpp
RESOURCES += QQ.qrc
